# coding: utf-8

"""
    SENSE-O Northbound Intent API

    StackV SENSE-O Northbound REST API Documentation  # noqa: E501

    OpenAPI spec version: 2.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Bandwidth(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'capacity': 'str',
        'unit': 'str',
        'qos_class': 'str'
    }

    attribute_map = {
        'capacity': 'capacity',
        'unit': 'unit',
        'qos_class': 'qos_class'
    }

    def __init__(self, capacity=None, unit=None, qos_class=None):  # noqa: E501
        """Bandwidth - a model defined in Swagger"""  # noqa: E501
        self._capacity = None
        self._unit = None
        self._qos_class = None
        self.discriminator = None
        if capacity is not None:
            self.capacity = capacity
        if unit is not None:
            self.unit = unit
        if qos_class is not None:
            self.qos_class = qos_class

    @property
    def capacity(self):
        """Gets the capacity of this Bandwidth.  # noqa: E501


        :return: The capacity of this Bandwidth.  # noqa: E501
        :rtype: str
        """
        return self._capacity

    @capacity.setter
    def capacity(self, capacity):
        """Sets the capacity of this Bandwidth.


        :param capacity: The capacity of this Bandwidth.  # noqa: E501
        :type: str
        """

        self._capacity = capacity

    @property
    def unit(self):
        """Gets the unit of this Bandwidth.  # noqa: E501


        :return: The unit of this Bandwidth.  # noqa: E501
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this Bandwidth.


        :param unit: The unit of this Bandwidth.  # noqa: E501
        :type: str
        """

        self._unit = unit

    @property
    def qos_class(self):
        """Gets the qos_class of this Bandwidth.  # noqa: E501


        :return: The qos_class of this Bandwidth.  # noqa: E501
        :rtype: str
        """
        return self._qos_class

    @qos_class.setter
    def qos_class(self, qos_class):
        """Sets the qos_class of this Bandwidth.


        :param qos_class: The qos_class of this Bandwidth.  # noqa: E501
        :type: str
        """

        self._qos_class = qos_class

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Bandwidth, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Bandwidth):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
