# coding: utf-8

"""
    SENSE-O Northbound Intent API

    StackV SENSE-O Northbound REST API Documentation  # noqa: E501

    OpenAPI spec version: 2.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConnectionTerminals(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'vlan_tag': 'str',
        'ipv4_prefix_list': 'str',
        'uri': 'str',
        'assign_ip': 'bool',
        'mac_address_list': 'str'
    }

    attribute_map = {
        'name': 'name',
        'vlan_tag': 'vlan_tag',
        'ipv4_prefix_list': 'ipv4_prefix_list',
        'uri': 'uri',
        'assign_ip': 'assign_ip',
        'mac_address_list': 'mac_address_list'
    }

    def __init__(self, name=None, vlan_tag='any', ipv4_prefix_list=None, uri=None, assign_ip=None, mac_address_list=None):  # noqa: E501
        """ConnectionTerminals - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._vlan_tag = None
        self._ipv4_prefix_list = None
        self._uri = None
        self._assign_ip = None
        self._mac_address_list = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if vlan_tag is not None:
            self.vlan_tag = vlan_tag
        if ipv4_prefix_list is not None:
            self.ipv4_prefix_list = ipv4_prefix_list
        self.uri = uri
        if assign_ip is not None:
            self.assign_ip = assign_ip
        if mac_address_list is not None:
            self.mac_address_list = mac_address_list

    @property
    def name(self):
        """Gets the name of this ConnectionTerminals.  # noqa: E501

        Reference name for the terminal.  # noqa: E501

        :return: The name of this ConnectionTerminals.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConnectionTerminals.

        Reference name for the terminal.  # noqa: E501

        :param name: The name of this ConnectionTerminals.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def vlan_tag(self):
        """Gets the vlan_tag of this ConnectionTerminals.  # noqa: E501

        Optional VLAN tag for the terminal.  # noqa: E501

        :return: The vlan_tag of this ConnectionTerminals.  # noqa: E501
        :rtype: str
        """
        return self._vlan_tag

    @vlan_tag.setter
    def vlan_tag(self, vlan_tag):
        """Sets the vlan_tag of this ConnectionTerminals.

        Optional VLAN tag for the terminal.  # noqa: E501

        :param vlan_tag: The vlan_tag of this ConnectionTerminals.  # noqa: E501
        :type: str
        """

        self._vlan_tag = vlan_tag

    @property
    def ipv4_prefix_list(self):
        """Gets the ipv4_prefix_list of this ConnectionTerminals.  # noqa: E501

        Optional list of IPV4 prefixes.  # noqa: E501

        :return: The ipv4_prefix_list of this ConnectionTerminals.  # noqa: E501
        :rtype: str
        """
        return self._ipv4_prefix_list

    @ipv4_prefix_list.setter
    def ipv4_prefix_list(self, ipv4_prefix_list):
        """Sets the ipv4_prefix_list of this ConnectionTerminals.

        Optional list of IPV4 prefixes.  # noqa: E501

        :param ipv4_prefix_list: The ipv4_prefix_list of this ConnectionTerminals.  # noqa: E501
        :type: str
        """

        self._ipv4_prefix_list = ipv4_prefix_list

    @property
    def uri(self):
        """Gets the uri of this ConnectionTerminals.  # noqa: E501

        Terminal URI.  # noqa: E501

        :return: The uri of this ConnectionTerminals.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this ConnectionTerminals.

        Terminal URI.  # noqa: E501

        :param uri: The uri of this ConnectionTerminals.  # noqa: E501
        :type: str
        """
        if uri is None:
            raise ValueError("Invalid value for `uri`, must not be `None`")  # noqa: E501

        self._uri = uri

    @property
    def assign_ip(self):
        """Gets the assign_ip of this ConnectionTerminals.  # noqa: E501

        [[TODO: clarification]]  # noqa: E501

        :return: The assign_ip of this ConnectionTerminals.  # noqa: E501
        :rtype: bool
        """
        return self._assign_ip

    @assign_ip.setter
    def assign_ip(self, assign_ip):
        """Sets the assign_ip of this ConnectionTerminals.

        [[TODO: clarification]]  # noqa: E501

        :param assign_ip: The assign_ip of this ConnectionTerminals.  # noqa: E501
        :type: bool
        """

        self._assign_ip = assign_ip

    @property
    def mac_address_list(self):
        """Gets the mac_address_list of this ConnectionTerminals.  # noqa: E501

        [[TODO: clarification]]  # noqa: E501

        :return: The mac_address_list of this ConnectionTerminals.  # noqa: E501
        :rtype: str
        """
        return self._mac_address_list

    @mac_address_list.setter
    def mac_address_list(self, mac_address_list):
        """Sets the mac_address_list of this ConnectionTerminals.

        [[TODO: clarification]]  # noqa: E501

        :param mac_address_list: The mac_address_list of this ConnectionTerminals.  # noqa: E501
        :type: str
        """

        self._mac_address_list = mac_address_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConnectionTerminals, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectionTerminals):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
