# coding: utf-8

"""
    SENSE-O Northbound Intent API

    StackV SENSE-O Northbound REST API Documentation  # noqa: E501

    OpenAPI spec version: 2.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Delta(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'val': 'str'
    }

    attribute_map = {
        'id': 'id',
        'val': 'val'
    }

    def __init__(self, id=None, val=None):  # noqa: E501
        """Delta - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._val = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if val is not None:
            self.val = val

    @property
    def id(self):
        """Gets the id of this Delta.  # noqa: E501

        Service intent UUID.  # noqa: E501

        :return: The id of this Delta.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Delta.

        Service intent UUID.  # noqa: E501

        :param id: The id of this Delta.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def val(self):
        """Gets the val of this Delta.  # noqa: E501

        The service delta itself, in JSON string format.  # noqa: E501

        :return: The val of this Delta.  # noqa: E501
        :rtype: str
        """
        return self._val

    @val.setter
    def val(self, val):
        """Sets the val of this Delta.

        The service delta itself, in JSON string format.  # noqa: E501

        :param val: The val of this Delta.  # noqa: E501
        :type: str
        """

        self._val = val

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Delta, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Delta):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
