# coding: utf-8

"""
    SENSE-O Northbound Intent API

    StackV SENSE-O Northbound REST API Documentation  # noqa: E501

    OpenAPI spec version: 2.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LoggingConfigurationLoggers(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'console': 'str',
        'database': 'str'
    }

    attribute_map = {
        'console': 'console',
        'database': 'database'
    }

    def __init__(self, console=None, database=None):  # noqa: E501
        """LoggingConfigurationLoggers - a model defined in Swagger"""  # noqa: E501
        self._console = None
        self._database = None
        self.discriminator = None
        if console is not None:
            self.console = console
        if database is not None:
            self.database = database

    @property
    def console(self):
        """Gets the console of this LoggingConfigurationLoggers.  # noqa: E501

        Logging of this level or higher will be printed to server console.  # noqa: E501

        :return: The console of this LoggingConfigurationLoggers.  # noqa: E501
        :rtype: str
        """
        return self._console

    @console.setter
    def console(self, console):
        """Sets the console of this LoggingConfigurationLoggers.

        Logging of this level or higher will be printed to server console.  # noqa: E501

        :param console: The console of this LoggingConfigurationLoggers.  # noqa: E501
        :type: str
        """

        self._console = console

    @property
    def database(self):
        """Gets the database of this LoggingConfigurationLoggers.  # noqa: E501

        Logging of this level or higher will be logged to database.  # noqa: E501

        :return: The database of this LoggingConfigurationLoggers.  # noqa: E501
        :rtype: str
        """
        return self._database

    @database.setter
    def database(self, database):
        """Sets the database of this LoggingConfigurationLoggers.

        Logging of this level or higher will be logged to database.  # noqa: E501

        :param database: The database of this LoggingConfigurationLoggers.  # noqa: E501
        :type: str
        """

        self._database = database

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LoggingConfigurationLoggers, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LoggingConfigurationLoggers):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
